### ISSUE TITLE
Is it possible to use this package with sequelize in nestjs?  Getting errors with basic implementation

### ISSUE THREAD

**Issue by isaackearl** [nartc/mapper#266]
I'm on the latest version of the following packages in a nestjs project with sequelize
```
    "@automapper/classes": "^3.0.8",
    "@automapper/core": "^3.0.8",
    "@automapper/nestjs": "^3.0.8",
    "@automapper/types": "^3.0.8",
```

I'm running into several problems while trying to use this package to convert sequelize models into and out of dtos.

The only way I can get it to work is with the most basic mapping ie ```mapper.createMap(Mark, MarkDto);```, and then using AutoMap() on all the properties I want to map.  The fluent syntax provided by your package for using the methods on MemberMapFunction. don't work for me at all.  

Here is my basic setup that I can't get to work and the error I receive:

my profile
```
@Injectable()
export class MarksMapperProfile extends AutomapperProfile {
  constructor(
    @InjectMapper() mapper: Mapper,
    @InjectModel(Mark) private markModel: typeof Mark
  ) {
    super(mapper);
  }

  mapProfile() {
    return (mapper) => {
      mapper
        .createMap(Mark, MarkDto)
        .forMember((destination) => destination.isArchived),
        mapFrom((source) => source.isArchived);
      mapper
        .createMap(MarkDto, Mark)
        .forMember((destination) => destination.isArchived),
        mapFrom((source) => source.isArchived);
    };
  }
}
```

how it is included in app.module
```
@Module({
  imports: [
    AutomapperModule.forRoot({
      options: [
        {
          name: "mapper",
          pluginInitializer: classes,
          namingConventions: new CamelCaseNamingConvention()
        }
      ],
      singular: true
    }),
...
```

As you can see All i'm trying to do is map 1 property "isArchived" between the 2 classes.  
Both of these classes are identical other than one is a sequelize model and the other is a Dto.  If I put AutoMap() on both of these properties and remove this fluid syntax, then it works, however I'm trying to get the fluent syntax to work so that I can use that to map relationships that aren't exact matches.

in my service layer I have something like this:
```
  async findAll(): Promise<MarkDto[]> {
    const marks = await this.markModel.findAll();
    return this.mapper.mapArray(marks, MarkDto, Mark);
  }
```
I've tried single mapping and all sorts of different things, however it doesn't work no matter what I try here.

the error I'm getting is this:
```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at Object.createMapForMember (C:\project\node_modules\@automapper\core\src\lib\create-mapper\create-map-for-member.util.js:25:20)
    at Object.forMember (C:\project\node_modules\@automapper\core\src\lib\create-mapper\create-map-fluent-function.util.js:14:49)
    at C:\project\dist\mappers\marks.mapper-profile.js:31:18
    at Object.addProfile (C:\project\node_modules\@automapper\core\src\lib\create-mapper\create-mapper.js:30:13)
    at C:\project\node_modules\@automapper\nestjs\src\lib\abstracts\automapper-profile.abstract.js:7:50
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:7660) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

If I remove the fluent mappings and at at least 1 AutoMap() property in the 2 classes then this error goes away.  If I don't add an AutoMap() property then I get another error which makes sense because I don't have any items to map.

Anyway, any clue about how to get this to work would be greatly appreciated.  Love the package and I think the documentation is great.  I am a c# developer originally and used Automapper there, so I was very happy to find this available.

**Comment by nartc** [comment]
@isaackearl Thanks for the kind words and thanks for opening the issue. It looks like the syntax on your forMember is wrong a bit.

```ts
// you have
.forMember((destination) => destination.isArchived), mapFrom(...)

// correct
.forMember((destination) => destination.isArchived, mapFrom(...))
```

`mapFrom(...)` is still a part of forMember. Can you confirm that?

**Comment by isaackearl** [comment]
@nartc OK so that made it partially work.  Thank you so much.  

Here is my new situation:  If I am mapping the two classes above without using AutoMap() at all, and only using the fluent syntax I get the following error:
```
(node:25728) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at Object.getNestedMetaKeyAtDestinationPath (C:\project\node_modules\@automapper\core\src\lib\initialize-utils\get-nested-metakey-at-destination-path.util.js:8:31)
    at Object.createInitialMapping (C:\project\node_modules\@automapper\core\src\lib\initialize-utils\create-initial-mapping.util.js:39:95)
    at Object.initializeMapping (C:\project\node_modules\@automapper\classes\src\lib\classes.js:45:27)
    at Object.createMap (C:\project\node_modules\@automapper\core\src\lib\create-mapper\create-mapper.js:24:36)
    at C:\project\dist\mappers\marks.mapper-profile.js:30:20
    at Object.addProfile (C:\project\node_modules\@automapper\core\src\lib\create-mapper\create-mapper.js:30:13)
    at C:\project\node_modules\@automapper\nestjs\src\lib\abstracts\automapper-profile.abstract.js:7:50
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:25728) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:25728) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

If I add AutoMap() to another property... say the "id", then the mapping works.  I get both the isArchived attribute and the id.  I was hoping to handle the mapping completely in the Profile so I don't really want to use the AutoMap() decorator (at least in some cases).  Is this normal, or a valid issue?

**Comment by nartc** [comment]
That looks like a valid issue to me, probably some use-case that I didn’t anticipate. You say that you don’t have any AutoMap and just use Fluent API correct? I’ll give that a try on my tests to see if I can reproduce. Thanks!

**Comment by isaackearl** [comment]
thanks @nartc I appreciate that.

**Comment by nartc** [comment]
@isaackearl Are you able to provide a sample reproduce? I can't seem to reproduce that issue.

**Comment by isaackearl** [comment]
@nartc I think it must be related specifically to the nestjs implementation.  I'll try and make a sample project to verify.

**Comment by nartc** [comment]
@isaackearl Can you provide me your Mark and MarkDto models?

**Comment by isaackearl** [comment]
@nartc I've created a very simple project.  Is there a way I can send to you?  I'll paste as much as I can here:

![image](https://user-images.githubusercontent.com/9354830/109338523-63077e00-7834-11eb-8aee-f8690132ffad.png)

foo.dto.ts
```
export class FooDto {
  public id?: number;
  public bar: string;
}

```
foo.entity.ts
```
import { Column, Model, PrimaryKey, Table } from 'sequelize-typescript';

@Table
export class Foo extends Model<Foo> {
  @PrimaryKey
  @Column
  public id?: number;

  @Column
  public bar: string;
}

```
foo.mapper-profile.ts
```
import { AutomapperProfile, InjectMapper } from '@automapper/nestjs';
import type { Mapper } from '@automapper/types';
import { Injectable } from '@nestjs/common';
import { Foo } from '../entities/foo.entity';
import { FooDto } from '../dto/foo.dto';
import { mapFrom } from '@automapper/core';

@Injectable()
export class FooMapperProfile extends AutomapperProfile {
  constructor(@InjectMapper() mapper: Mapper) {
    super(mapper);
  }

  mapProfile() {
    return (mapper) => {
      mapper.createMap(Foo, FooDto).forMember(
        (destination) => destination.bar,
        mapFrom((source) => source.bar),
      );
      mapper.createMap(FooDto, Foo).forMember(
        (destination) => destination.bar,
        mapFrom((source) => source.bar),
      );
    };
  }
}
```
foo.controller.ts
```
import { Controller, Get, Param } from '@nestjs/common';
import { FoosService } from './foos.service';

@Controller('foos')
export class FoosController {
  constructor(private readonly foosService: FoosService) {}

  @Get(':id')
  findOne(@Param('id') id: string) {
    return this.foosService.findOne(+id);
  }
}
```
foo.service.ts
```
import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/sequelize';
import { Foo } from './entities/foo.entity';
import { InjectMapper } from '@automapper/nestjs';
import type { Mapper } from '@automapper/types';
import { FooDto } from './dto/foo.dto';

@Injectable()
export class FoosService {
  constructor(
    @InjectModel(Foo) private fooModel: typeof Foo,
    @InjectMapper() private mapper: Mapper,
  ) {}

// here is me trying to use the mapper
  findOne(id: number) {
    const foo = new Foo();
    foo.bar = 'baz';
    return this.mapper.map(foo, FooDto, Foo);
  }
}

```
app.module
```
import { Module } from '@nestjs/common';
import { SequelizeModule } from '@nestjs/sequelize';
import { FoosModule } from './foos/foos.module';
import { AutomapperModule } from '@automapper/nestjs';
import { classes } from '@automapper/classes';

@Module({
  imports: [
    AutomapperModule.forRoot({
      options: [{ name: 'mapper', pluginInitializer: classes }],
      singular: true,
    }),
    SequelizeModule.forRoot({
      dialect: 'postgres',
      host: 'localhost',
      port: 5432,
      username: 'postgres',
      password: '',
      database: 'test',
      autoLoadModels: true,
      synchronize: true,
    }),
    FoosModule,
  ],

  controllers: [],
  providers: [],
})
export class AppModule {}

```
main.ts
```
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  app.setGlobalPrefix('api');
  await app.listen(8080);
}
bootstrap();
```

This is all the files.  it works if I add AutoMap() to one of the properties (id) of both models.  If I don't have AutoMap() on there, then I get this error when running it: 

```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at Object.getNestedMetaKeyAtDestinationPath (C:\Code\js\nestjs\sequelize\node_modules\@automapper\core\src\lib\initialize-utils\get-nested-metakey-at-destination-path.util.js:8:31)
    at Object.createInitialMapping (C:\Code\js\nestjs\sequelize\node_modules\@automapper\core\src\lib\initialize-utils\create-initial-mapping.util.js:39:95)
    at Object.initializeMapping (C:\Code\js\nestjs\sequelize\node_modules\@automapper\classes\src\lib\classes.js:45:27)
    at Object.createMap (C:\Code\js\nestjs\sequelize\node_modules\@automapper\core\src\lib\create-mapper\create-mapper.js:24:36)
    at C:\Code\js\nestjs\sequelize\dist\foos\profiles\foo.mapper-profile.js:28:20
    at Object.addProfile (C:\Code\js\nestjs\sequelize\node_modules\@automapper\core\src\lib\create-mapper\create-mapper.js:30:13)
    at C:\Code\js\nestjs\sequelize\node_modules\@automapper\nestjs\src\lib\abstracts\automapper-profile.abstract.js:7:50
(node:21420) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:21420) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by nartc** [comment]
@isaackearl can you make upload that to a repository in github here? and share me the repo link? I'll clone it down and check it out

**Comment by isaackearl** [comment]
@nartc 

Here you go. https://github.com/isaackearl/sequelize-automapper-nestjs

 I was using postgres so you might have to change to a different one in order to get it to build without getting angry.

I'm on node version 12.20.2 npm version 6.14.11

**Comment by nartc** [comment]
@isaackearl Try version 3.0.9 out and lemme know if you still have issues.

**Comment by isaackearl** [comment]
@nartc this might sound dumb but I can't figure out how to install 3.0.9.  I see it in https://www.npmjs.com that there are new versions for the various packages (3.0.9)... but when I run update and/or try and manually put 3.0.9 in my package.json, it says no matching version.  I'm guessing I just need to wait a bit for things to propagate.  Unless there is a way to download the various packages directly from github?  I've done that in the past but don't know how to do it for packages that aren't the main repo.

**Comment by nartc** [comment]
@isaackearl you can just go to `package.json` and change `3.0.8` to `3.0.9` on

```
@automapper/core: "3.0.9",
@automapper/nestjs: "3.0.9",
@automapper/classes: "3.0.9",
@automapper/types: "3.0.9",
```

**Comment by isaackearl** [comment]
ah @nartc I forgot that my npm points at a nexus repository, I lowered the cache time and then it started working.

Also, it looks to me like it is totally working now.  Thanks for fixing that!  I think I've found one other issue but it is unrelated to this, so I'll open that in a new issue (if I can't figure out how to fix it).

Thanks for your help!
