### ISSUE TITLE
Extends class makes compiles error when using with nestjs

### ISSUE THREAD

**Issue by s-triar** [nartc/mapper#308]
Currently, I am working on a project with angular + nestjs/ng-universal.
But right now, I am getting stuck on why this automapper get this error when I create source class and destination class with extends class.

```
Unhandled Promise rejection: Cannot read property '1' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property '1' of undefined
    at Object.extendMappings (D:\Professional\guitarTracking\dist\guitarTracking\server\main.js:98230:46)
    at Object.createInitialMapping (D:\Professional\guitarTracking\dist\guitarTracking\server\main.js:98208:28)
    at Object.initializeMapping (D:\Professional\guitarTracking\dist\guitarTracking\server\main.js:97102:27)
    at Object.createMap (D:\Professional\guitarTracking\dist\guitarTracking\server\main.js:97970:36)
    at D:\Professional\guitarTracking\dist\guitarTracking\server\main.js:459882:20
    at Object.addProfile (D:\Professional\guitarTracking\dist\guitarTracking\server\main.js:97976:13)
    at D:\Professional\guitarTracking\dist\guitarTracking\server\main.js:99393:50
    at ZoneDelegate.invoke (D:\Professional\guitarTracking\dist\guitarTracking\server\main.js:457093:160)
    at Zone.run (D:\Professional\guitarTracking\dist\guitarTracking\server\main.js:456819:37)
    at D:\Professional\guitarTracking\dist\guitarTracking\server\main.js:458160:28 TypeError: Cannot read property '1' of undefined
    at Object.extendMappings (D:\Professional\guitarTracking\dist\guitarTracking\server\main.js:98230:46)
    at Object.createInitialMapping (D:\Professional\guitarTracking\dist\guitarTracking\server\main.js:98208:28)
    at Object.initializeMapping (D:\Professional\guitarTracking\dist\guitarTracking\server\main.js:97102:27)
    at Object.createMap (D:\Professional\guitarTracking\dist\guitarTracking\server\main.js:97970:36)
    at D:\Professional\guitarTracking\dist\guitarTracking\server\main.js:459882:20
    at Object.addProfile (D:\Professional\guitarTracking\dist\guitarTracking\server\main.js:97976:13)
    at D:\Professional\guitarTracking\dist\guitarTracking\server\main.js:99393:50
    at ZoneDelegate.invoke (D:\Professional\guitarTracking\dist\guitarTracking\server\main.js:457093:160)
    at Zone.run (D:\Professional\guitarTracking\dist\guitarTracking\server\main.js:456819:37)
    at D:\Professional\guitarTracking\dist\guitarTracking\server\main.js:458160:28
```

Here are the module and profiles

app.module.ts
```
import { Module } from '@nestjs/common';
import { AngularUniversalModule } from '@nestjs/ng-universal';
import { TypeOrmModule } from '@nestjs/typeorm';
import { join } from 'path';
import { AppServerModule } from '../src/main.server';
import { environment } from './environment/environtment.server';
import { User } from './user/User.entity';
import { UserModule } from './user/user.module';
import { AutomapperModule } from '@automapper/nestjs';
import { classes } from '@automapper/classes';
import { DateAuditMapperProfile } from './classes/date-audit-mapper.profile';

@Module({
  imports: [
    AngularUniversalModule.forRoot({
      bootstrap: AppServerModule,
      viewsPath: join(process.cwd(), 'dist/guitarTracking/browser')
    }),
    TypeOrmModule.forRoot({
      type: "mysql",
      host: "localhost",
      port: 3306,
      username: "root",
      password: "root",
      database: "somedb",
      entities: [User],
      synchronize: true
    }),
    UserModule,
    AutomapperModule.forRoot({
      options: [{ name: 'classMapper', pluginInitializer: classes }],
      singular: true,
    }),
  ],
  providers:[
    DateAuditMapperProfile
  ],
  controllers: []
})
export class AppModule {}

```
date-audit-mapper.profile.ts
```
import { InjectMapper, AutomapperProfile } from '@automapper/nestjs';
import { Mapper, MappingProfile } from '@automapper/types';
import { Injectable } from '@nestjs/common';
import { DateAudit, DateAuditEntity } from 'server/common-entities/date-audit.entity';
import { DateAuditDTO } from './date-audit-dto';
import { AutoMap } from '@automapper/classes';
@Injectable()
export class DateAuditMapperProfile extends AutomapperProfile  {
  constructor(@InjectMapper() mapper: Mapper) {
    super(mapper);
}
  mapProfile(): MappingProfile {
    return mapper => {
        mapper.createMap(DateAuditEntity, DateAuditDTO);
    }
  }
}
export class DateAuditDTO{
    @AutoMap()
    createdAt!: Date;
    @AutoMap()
    createdBy!: string;
    @AutoMap()
    updatedAt!: Date;
    @AutoMap()
    updatedBy!: string;
    @AutoMap()
    deletedAt!: Date;
    @AutoMap()
    deletedBy!: string;
    @AutoMap()
    deleteDescription!: string;
}
export class DateAuditEntity{
  @AutoMap()
  createdAt!: Date;
  @AutoMap()
  createdBy!: string;
  @AutoMap()
  updatedAt!: Date;
  @AutoMap()
  updatedBy!: string;
  @AutoMap()
  deletedAt!: Date;
  @AutoMap()
  deletedBy!: string;
  @AutoMap()
  deleteDescription!: string;
}
```
user.module.ts
```
import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { User } from './User.entity';
import { UserController } from './user.controller';
import { UserService } from './user.service';
import { UserMapperProfile } from 'server/classes/user-mapper.profile';
import { DateAuditMapperProfile } from 'server/classes/date-audit-mapper.profile';

@Module({
  imports:[TypeOrmModule.forFeature([User])],
  controllers: [UserController],
  providers: [UserService, UserMapperProfile]
})
export class UserModule {}

```
user-mapper.profile.ts
```
import { InjectMapper, AutomapperProfile } from '@automapper/nestjs';
import { Mapper, MappingProfile } from '@automapper/types';
import { Injectable } from '@nestjs/common';
import { DateAudit, DateAuditEntity } from 'server/common-entities/date-audit.entity';
import { User, UserEntity } from 'server/user/User.entity';
import { DateAuditDTO } from './date-audit-dto';
import { UserDTO } from './user-dto';
import { mapFrom } from '@automapper/core';
import { AutoMap } from '@automapper/classes';

@Injectable()
export class UserMapperProfile extends AutomapperProfile  {
  constructor(@InjectMapper() mapper: Mapper) {
    super(mapper);
}
  mapProfile(): MappingProfile {
    return mapper => {
        mapper.createMap(UserEntity, UserDTO, { extends: [mapper.getMapping(DateAuditEntity, DateAuditDTO)] });
    }
  }
  
}
export class UserEntity extends DateAuditEntity{
  @AutoMap()
  id!: number;
  @AutoMap()
  name!: string;
  @AutoMap()
  station!: number;
  @AutoMap()
  password!: string;
  @AutoMap()
  email!: string;
  @AutoMap()
  phone!: string;
}
export class UserDTO extends DateAuditDTO{
    @AutoMap()
    id!:number;
    @AutoMap()
    name!:string;
    @AutoMap()
    station!:number;
    @AutoMap()
    email!:string;
    @AutoMap()
    phone!:string;
}
```

**Comment by micalevisk** [comment]
Hi! which version of `@automapper/*` are you using?

**Comment by s-triar** [comment]
> Hi! which version of `@automapper/*` are you using?
I am using these:
```"@automapper/classes": "^4.2.0",
"@automapper/core": "^4.2.0",
"@automapper/nestjs": "^4.2.0",
"@automapper/pojos": "^4.2.0",```

**Comment by nartc** [comment]
Taking a look at the end of today. Thanks for reporting

**Comment by nartc** [comment]
Hi @s-triar , this is due to how NestJS Dependency Injection works. Best way to solve this is to move your `DateAuditMapperProfile` to `DateAuditModule` 

```ts
@Module({
   providers: [DateAuditMapperProfile]
})
export class DateAuditModule {}
```

and then import `DateAuditModule` in `AppModule`. I'd also suggest move `AutomapperModule` import in front of your modules

```ts
@Module({
   imports: [
      // your 3rd party modules,
      AutomapperModule.forRoot(...),
      DateAuditModule,
      UserModule
   ]
})
export class AppModule {}
```

**Comment by nartc** [comment]
Closing due to inactivity. Please open a new issue if you still have questions.
