### ISSUE TITLE
Mapping classes containing fields of type Buffer fails

### ISSUE THREAD

**Issue by aki-ks** [nartc/mapper#406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Whenever a class contains some field of Node's `Buffer`-type, then AutoMapper fails to create a mapping for that class.

### Models/DTOs/VMs

```typescript
class FooDto {
  @AutoMap()
  a: Buffer;
}

class FooEntity {
  @AutoMap()
  a: Buffer;
}

```

### Mapping configuration

```typescript
const mapper = createMapper({
  name: 'default',
  pluginInitializer: classes,
});

mapper.createMap(FooDto, FooEntity);
```

### Steps to reproduce

```typescript
// index.ts
const mapper = createMapper({
  name: 'default',
  pluginInitializer: classes,
});

mapper.createMap(FooDto, FooEntity);
```

```
$ ts-node index.ts
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at Function.from (https://node-dwtufw.w.staticblitz.com/blitz.d4ed89204e54de5c40d109298317e6dc4d60aef7.js:6:41124)
    at new Buffer (https://node-dwtufw.w.staticblitz.com/blitz.d4ed89204e54de5c40d109298317e6dc4d60aef7.js:6:40345)
    at instantiate (/home/projects/node-dwtufw/packages/classes/src/lib/utils/instantiate.util.ts:129:9)
    at Object.instantiate (/home/projects/node-dwtufw/packages/classes/src/lib/classes.ts:32:25)
    at Object.initializeMapping (/home/projects/node-dwtufw/packages/classes/src/lib/classes.ts:58:14)
    at Object.createMap (/home/projects/node-dwtufw/packages/core/src/lib/create-mapper/create-mapper.ts:66:30)
    at Object.eval (/home/projects/node-dwtufw/index.ts:19:8)
    at Object.function (https://node-dwtufw.w.staticblitz.com/blitz.d4ed89204e54de5c40d109298317e6dc4d60aef7.js:11:114508)
    at Module._compile (https://node-dwtufw.w.staticblitz.com/blitz.d4ed89204e54de5c40d109298317e6dc4d60aef7.js:6:167880)
    at Module.m._compile (/home/projects/node-dwtufw/node_modules/ts-node/src/index.ts:1371:23) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

### Expected behavior

AutoMapper should create Mappings for classes containing fields of Nodes Buffer-type without failing.
In the given example a `FooDto` should be mappable to a `FooEntity`.
The `Buffer` in the `FooDto.a` field should be mapped automatically to the `FooEntity.a` field.

```typescript
const dto = new FooDto();
dto.a = new Buffer('foo');

const entity = mapper.map(dto, FooEntity, FooDto);
console.log(entity);

// expected output (instead of thrown error):
// FooDto { a: <Buffer 66 6f 6f> }
```

### Minimum reproduction code

https://stackblitz.com/edit/node-kwrwqq?devtoolsheight=33&file=index.ts

### Package

- [ ] I don't know.
- [X] <code>@automapper/core</code>
- [X] <code>@automapper/classes</code>
- [ ] <code>@automapper/nestjs</code>
- [ ] <code>@automapper/pojos</code>
- [ ] <code>@automapper/sequelize</code>
- [X] <code>@automapper/types</code>
- [ ] Other (see below)

### AutoMapper version

7.2.1

**Comment by nartc** [comment]
This should be fixed with AutoMapper v8. Since `Buffer` type needs to be instantiated in v7 and v7 does not provide custom constructor (which it seems like `Buffer` needs it), this cannot be fixed in v7 unfortunately.
