### ISSUE TITLE
please fix Circular Dependencies with pojos

### ISSUE THREAD

**Issue by zieglar** [nartc/mapper#407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

two interface, faceA many to one faceB, faceB has one faceA, when application start, log error
```
(node:12095) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    at instantiate (xxx/packages/pojos/src/lib/utils/instantiate.util.ts:13:28)
    at instantiate (xxx/packages/pojos/src/lib/utils/instantiate.util.ts:81:22)
    at instantiate (xxx/packages/pojos/src/lib/utils/instantiate.util.ts:81:22)
    at instantiate (xxx/packages/pojos/src/lib/utils/instantiate.util.ts:81:22)
    at instantiate (xxx/packages/pojos/src/lib/utils/instantiate.util.ts:81:22)
    at instantiate (xxx/packages/pojos/src/lib/utils/instantiate.util.ts:81:22)
    at instantiate (xxx/packages/pojos/src/lib/utils/instantiate.util.ts:81:22)
    at instantiate (xxx/packages/pojos/src/lib/utils/instantiate.util.ts:81:22)
    at instantiate (xxx/packages/pojos/src/lib/utils/instantiate.util.ts:81:22)
    at instantiate (xxx/packages/pojos/src/lib/utils/instantiate.util.ts:81:22)
```

if I comment any one in `createMetadataMap` function, application start normal.

### Models/DTOs/VMs
```
interface faceA {
  bs: faceB[]
}
interface faceB {
 a: faceA
}
createMetadataMap('faceA', {
  bs: 'faceB'
})
createMetadataMap('faceB', {
  a: 'faceA'
})
```

### Expected behavior

normal mapping pojos relation.

### Minimum reproduction code

[https://stackblitz.com/edit/typescript-automapper-cswvej?file=index.ts](https://stackblitz.com/edit/typescript-automapper-cswvej?file=index.ts)

### Package

- [ ] I don't know.
- [ ] <code>@automapper/core</code>
- [ ] <code>@automapper/classes</code>
- [ ] <code>@automapper/nestjs</code>
- [X] <code>@automapper/pojos</code>
- [ ] <code>@automapper/sequelize</code>
- [ ] <code>@automapper/types</code>
- [ ] Other (see below)

### AutoMapper version

    "@automapper/core": "^7.3.14",
    "@automapper/nestjs": "^7.3.14",
    "@automapper/pojos": "^7.3.14",

### Additional context

MacOS
Node 14

**Comment by zieglar** [comment]
@nartc Hi, Is it possible to fix this circular Dependencies error in pojos ?

**Comment by nartc** [comment]
@zieglar sorry for the late response. Can you test this with AutoMapper v8?

**Comment by zieglar** [comment]
I'm still using v7 and will be migrating to v8 in the future, I found my own solution regarding the previous pojos circular dependency issue
