### ISSUE TITLE
NestJS Initialization Failing when AutoMap type self pointed twice

### ISSUE THREAD

**Issue by happyNariman** [nartc/mapper#455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

An error occurs when starting the project.
If there are two or more mappings to the same class

> /backend/node_modules/@automapper/core/index.cjs:755
  function applyMetadata(model) {
                        ^
RangeError: Maximum call stack size exceeded
    at applyMetadata (backend/node_modules/@automapper/core/index.cjs:755:25)
    at applyMetadata (backend/node_modules/@automapper/core/index.cjs:830:32)
    at applyMetadata (backend/node_modules/@automapper/core/index.cjs:830:32)
    at applyMetadata (backend/node_modules/@automapper/core/index.cjs:830:32)
    at applyMetadata (backend/node_modules/@automapper/core/index.cjs:830:32)
    at applyMetadata (backend/node_modules/@automapper/core/index.cjs:830:32)
    at applyMetadata (backend/node_modules/@automapper/core/index.cjs:830:32)
    at applyMetadata (backend/node_modules/@automapper/core/index.cjs:830:32)
    at applyMetadata (backend/node_modules/@automapper/core/index.cjs:830:32)
    at applyMetadata (backend/node_modules/@automapper/core/index.cjs:830:32)
The terminal process "/bin/bash '-c', 'npm run start'" terminated with exit code: 1.

### Models/DTOs/VMs

`export class UserEntity {

    @AutoMap(() => UserEntity)
    parent?: Types.ObjectId | UserEntity;

    @AutoMap(() => UserEntity)
    trainer?: Types.ObjectId | UserEntity;

}`

### Expected behavior

There shouldn't be any mistakes

### Package

- [ ] I don't know.
- [X] <code>@automapper/core</code>
- [ ] <code>@automapper/classes</code>
- [ ] <code>@automapper/nestjs</code>
- [ ] <code>@automapper/pojos</code>
- [ ] <code>@automapper/mikro</code>
- [ ] <code>@automapper/sequelize</code>
- [ ] Other (see below)

### AutoMapper version

8.2.3

**Comment by nartc** [comment]
Please provide a minimal reproduce repo.

**Comment by nartc** [comment]
@happyNariman Please test out 8.3.2
At least the error is gone and the `/get` route is working. Can you make sure that it is correct? If yes, please close the issue. Thank you for reporting

**Comment by happyNariman** [comment]
it works!
