### ISSUE TITLE
ignore() does not work as expected

### ISSUE THREAD

**Issue by joshua-schnabel** [nartc/mapper#456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

If an attempt is made to map an object into another object and an attribute is specified to be ignored, it is set to undefined. 
If the target object has no setter, and therefore the matching attributes are set to ignore, an error is thrown. 

If the object has setter, the following is returned:

```
RepoDto { id: 'test', path: '/test' }
Repo { _id: undefined, _path: undefined }
```

If the object has no setter, an error is output, although the attributes should not be written because of ignoring:

```
RepoDto { id: 'test', path: '/test' }
[AutoMapper]
Error at "path" on Repo ({"_id":{"_value":"test"},"_path":"/test"})
---------------------------------------------------------------------
Original error: TypeError: Cannot set property path of #<Repo> which has only a getter
Error:
Error at "path" on Repo ({"_id":{"_value":"test"},"_path":"/test"})
---------------------------------------------------------------------
Original error: TypeError: Cannot set property path of #<Repo> which has only a getter
    at setMember (file:///C:/Users/Joshua/Desktop/anthill-pot/node_modules/@automapper/core/index.esm.js:333:15)
    at map (file:///C:/Users/Joshua/Desktop/anthill-pot/node_modules/@automapper/core/index.esm.js:425:5)
    at mapReturn (file:///C:/Users/Joshua/Desktop/anthill-pot/node_modules/@automapper/core/index.esm.js:255:10)
    at Proxy.<anonymous> (file:///C:/Users/Joshua/Desktop/anthill-pot/node_modules/@automapper/core/index.esm.js:536:31)
    at file:///C:/Users/Joshua/Desktop/anthill-pot/src/test.ts:66:20
    at ModuleJob.run (node:internal/modules/esm/module_job:197:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)
```

### Models/DTOs/VMs

```
export class RepoId {
  private readonly _value: string;
  
  public constructor (value: string) {
    this._value = value;
  }
  
  public get value (): string {
    return this._value;
  }
}
export default class Repo {
    
  private _id: RepoId | undefined;
  private _path: string;
    
  public constructor (id: RepoId | undefined, path: string) {
    this._path = path;
    this._id = id;
  }
  
  @AutoMap()
  public get id (): RepoId | undefined {
    return this._id;
  }
  
  //public set id (id: RepoId | undefined) {
  //  this._id = id;
  //}
  
  @AutoMap()
  public get path (): string {
    return this._path;
  }
   
  //public set path (path: string) {
  //  this._path = path;
  //}
}

export class RepoDto {
  @AutoMap()
  public id!: string;

  @AutoMap()
  public path!: string;
}
```

### Mapping configuration

```
export const mapper = createMapper({
  strategyInitializer: classes()
});

createMap(mapper, Repo, RepoDto, forMember(
  (destination: RepoDto) => destination.id, mapFrom(s => s.id?.value)
));

createMap(mapper, RepoDto, Repo,
  forMember((d) => d.path, ignore()),
  forMember((d) => d.id, ignore()),
  constructUsing((sourceObject, _destinationIdentifier): Repo => {
    return new Repo(new RepoId(sourceObject.id), sourceObject.path);
  })
);
```

```
const x = new RepoDto();
x.id = "test";
x.path = "/test";

console.log(x);
console.log(mapper.map(x, RepoDto, Repo));
```

### Steps to reproduce

1.  node --loader ts-node/esm ./src/test.ts
2. See error

### Expected behavior

I would have expected that "constructUsing" would create my object (which seems to work) and by specifying "ignore" the attributes would not be set and therefore no setters would be necessary.

### Package

- [ ] I don't know.
- [X] <code>@automapper/core</code>
- [X] <code>@automapper/classes</code>
- [ ] <code>@automapper/nestjs</code>
- [ ] <code>@automapper/pojos</code>
- [ ] <code>@automapper/mikro</code>
- [ ] <code>@automapper/sequelize</code>
- [ ] Other (see below)

### AutoMapper version

8.2.3

### Additional context

Windows, yarn, esm

**Comment by joshua-schnabel** [comment]
Thank you very much, it seems to be running now. Here is my example:
```
import { AutoMap, classes } from "@automapper/classes";
import { constructUsing, createMap, createMapper, forMember, mapFrom } from "@automapper/core";

export const mapper = createMapper({
  strategyInitializer: classes()
});

export default class Repo {
    
  private readonly _id: string | undefined;
  private readonly _path: string;
    
  public constructor (id: string | undefined, path: string) {
    this._path = path;
    this._id = id;
  }
  
  @AutoMap()
  public get id (): string | undefined {
    return this._id;
  }
  
  @AutoMap()
  public get path (): string {
    return this._path;
  }
   
}

export class RepoDto {
  @AutoMap()
  public id!: string;

  @AutoMap()
  public path!: string;
}

createMap(mapper, Repo, RepoDto, forMember(
  (destination: RepoDto) => destination.id, mapFrom(s => s.id) // needed because of type string | undefined
));

createMap(mapper, RepoDto, Repo,
  constructUsing((sourceObject, _destinationIdentifier): Repo => {
    return new Repo(sourceObject.id, sourceObject.path);
  })
);

const y = new Repo("yyy", "/yyy");
console.log(y, "   ->   ");
console.log(mapper.map(y, Repo, RepoDto));

const x = new RepoDto();
x.id = "test";
x.path = "/test";

console.log(x, "   ->   ");
console.log(mapper.map(x, RepoDto, Repo));
```
