### ISSUE TITLE
AutoMapper cannot map to identical class

### ISSUE THREAD

**Issue by Alwinator** [nartc/mapper#460]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

I am mapping two classes that both have a field `role: RoleDto`. However, AutoMapper cannot map this by default instead I need to create a map: `createMap(mapper, RoleDto, RoleDto);
`

### Steps to reproduce

npm run start:dev

### Expected behavior

That AutoMapper does not need the mentioned map.

### Minimum reproduction code

https://github.com/Alwinator/automapper-map-self-bug

### Package

- [ ] I don't know.
- [X] <code>@automapper/core</code>
- [X] <code>@automapper/classes</code>
- [ ] <code>@automapper/nestjs</code>
- [ ] <code>@automapper/pojos</code>
- [ ] <code>@automapper/mikro</code>
- [ ] <code>@automapper/sequelize</code>
- [ ] Other (see below)

### AutoMapper version

8.3.2

### Additional context

Ubuntu 21.10
Node v16.13.1

**Comment by nartc** [comment]
Thanks for reporting. So if both fields on both sides (Source, Destination) of a Mapping contain RoleDto (or any same model), it should map as-is shouldn't it?

**Comment by Alwinator** [comment]
I get this error:
```
[Nest] 25839  - 04/12/2022, 8:45:37 PM   ERROR [ExceptionHandler] Mapping is not found for class RoleDto {
} and class RoleDto {
}
Error: Mapping is not found for class RoleDto {
} and class RoleDto {
}
    at getMapping (/home/alwin/WebStormsProjects/automapper-map-self-bug/node_modules/@automapper/core/index.cjs:110:11)
    at map (/home/alwin/WebStormsProjects/automapper-map-self-bug/node_modules/@automapper/core/index.cjs:398:31)
    at mapReturn (/home/alwin/WebStormsProjects/automapper-map-self-bug/node_modules/@automapper/core/index.cjs:264:10)
    at Proxy.<anonymous> (/home/alwin/WebStormsProjects/automapper-map-self-bug/node_modules/@automapper/core/index.cjs:568:31)
    at new AppService (/home/alwin/WebStormsProjects/automapper-map-self-bug/src/app.service.ts:23:36)
    at Injector.instantiateClass (/home/alwin/WebStormsProjects/automapper-map-self-bug/node_modules/@nestjs/core/injector/injector.js:330:19)
    at callback (/home/alwin/WebStormsProjects/automapper-map-self-bug/node_modules/@nestjs/core/injector/injector.js:48:41)
    at Injector.resolveConstructorParams (/home/alwin/WebStormsProjects/automapper-map-self-bug/node_modules/@nestjs/core/injector/injector.js:122:24)
    at Injector.loadInstance (/home/alwin/WebStormsProjects/automapper-map-self-bug/node_modules/@nestjs/core/injector/injector.js:52:9)
    at Injector.loadProvider (/home/alwin/WebStormsProjects/automapper-map-self-bug/node_modules/@nestjs/core/injector/injector.js:74:9)
```

However, when I add the following line it works perfectly:
```ts
createMap(mapper, RoleDto, RoleDto);
```

**Comment by Alwinator** [comment]
Thank you for fixing the bug! I've just tested it and it works perfectly!
