### ISSUE TITLE
TypeError: Cannot assign to read only property 'id' of object '#<Entity>'

### ISSUE THREAD

**Issue by Alwinator** [nartc/mapper#464]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

I am working with MikroORM and when I try to update elements in my database using 
```ts
wrap(e).assign(entity, { mergeObjects: true })
```

I get the following exception:
```
[Nest] 16513  - 04/18/2022, 2:08:32 PM   ERROR [ExceptionsHandler] Cannot assign to read only property 'id' of object '#<Tag>'
TypeError: Cannot assign to read only property 'id' of object '#<Tag>'
    at /home/alwin/WebStormsProjects/myproject/node_modules/@mikro-orm/core/dist/entity/EntityAssigner.js:65:37
    at Array.forEach (<anonymous>)
    at Function.assign (/home/alwin/WebStormsProjects/myproject/node_modules/@mikro-orm/core/dist/entity/EntityAssigner.js:29:27)
    at /home/alwin/WebStormsProjects/myproject/node_modules/@mikro-orm/core/dist/entity/EntityAssigner.js:135:47
    at Array.map (<anonymous>)
    at Function.assignCollection (/home/alwin/WebStormsProjects/myproject/node_modules/@mikro-orm/core/dist/entity/EntityAssigner.js:128:29)
    at /home/alwin/WebStormsProjects/myproject/node_modules/@mikro-orm/core/dist/entity/EntityAssigner.js:38:39
    at Array.forEach (<anonymous>)
    at Function.assign (/home/alwin/WebStormsProjects/myproject/node_modules/@mikro-orm/core/dist/entity/EntityAssigner.js:29:27)
    at WrappedEntity.assign (/home/alwin/WebStormsProjects/myproject/node_modules/@mikro-orm/core/dist/entity/WrappedEntity.js:49:48)
```
I map my Entities to Dtos using the code below
```ts
return this.mapper.map<Entity, Dto>(entity, this.entityIdentifier, this.dtoIdentifier)
```

I realized that when I add `wrap(entity).toObject()` the bug is fixed.
```ts
return this.mapper.map<Entity, Dto>(wrap(entity).toObject(), this.entityIdentifier, this.dtoIdentifier)
```

However, I think it should work without `wrap(entity).toObject()` because I am using the mikro strategy (`AutomapperModule.forRoot({strategyInitializer: mikro()})`)

The problem is that the id of the Tag object is read-only, but I have no read-only in my Dtos. I also tried to print the read-only state with and without the bug fix, however, they are the same.

```ts
element (writable) {
  tags (writable) {
    0 (writable) {
      name (writable)
      id (writable)
    }
  }
  ...
}
```

### Models/DTOs/VMs

ElementDto
```ts
import {AutoMap} from "@automapper/classes";
import {TagDto} from "../tag/tag.dto";


export class ElementDto{
  ...

  @AutoMap()
  tags: TagDto[]
}
```

TagDto
```ts
import {AutoMap} from "@automapper/classes";

export class TagDto{
  @AutoMap()
  id: number

  @AutoMap()
  name: string
}
```

### Mapping configuration

```ts
createMap(mapper, Tag, TagDto)
createMap(mapper, Element, ElementDto)
```

### Steps to reproduce

I am so sorry, but I tried for over 3 hours to reproduce the bug, but I was not successful. If you have any other ideas I can try them out in my project.

### Expected behavior

That is works without adding `wrap(entity).toObject()`

### Package

- [ ] I don't know.
- [X] <code>@automapper/core</code>
- [ ] <code>@automapper/classes</code>
- [ ] <code>@automapper/nestjs</code>
- [ ] <code>@automapper/pojos</code>
- [X] <code>@automapper/mikro</code>
- [ ] <code>@automapper/sequelize</code>
- [ ] Other (see below)

### AutoMapper version

8.0.0

### Additional context

Ubuntu 21.10
Node v16.13.1

**Comment by Alwinator** [comment]
@nartc It works! Thank you!
