### ISSUE TITLE
Error automap entities

### ISSUE THREAD

**Issue by jorgelperezr** [nartc/mapper#516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Hello, I have a problem when use automap decorator in the entities.
I have a project where there are entities, in one of them (taskEntity) there is a relation with other entity (deliveryInfo) and this last has a relation with driver entity.
Between DelveryInfo and driver entity exist a relation One to One and when I use automap decorator generate a error 

(node:17361) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    at applyMetadata (/Users/joperezre/Documents/proyectosGit/Backstore/receive/node_modules/@automapper/core/index.cjs:761:25)
    at applyMetadata (/Users/joperezre/Documents/proyectosGit/Backstore/receive/node_modules/@automapper/core/index.cjs:826:141)
    at applyMetadata (/Users/joperezre/Documents/proyectosGit/Backstore/receive/node_modules/@automapper/core/index.cjs:826:141)
    at applyMetadata (/Users/joperezre/Documents/proyectosGit/Backstore/receive/node_modules/@automapper/core/index.cjs:826:141)
    at applyMetadata (/Users/joperezre/Documents/proyectosGit/Backstore/receive/node_modules/@automapper/core/index.cjs:826:141)

entity code:
deliveryInfo

  @OneToOne(() => DriverEntity, (driver) => driver.deliveryInfo, {
    cascade: true,
    eager: false,
  })
  @AutoMap(() => DriverEntity)
  //@AutoMap()
  driver: DriverEntity;

driver

  @OneToOne(() => DeliveryInfoEntity, (deliveryInfo) => deliveryInfo.driver, {
    onDelete: 'CASCADE',
  })
  @Index('driver_deliverInfoId_index')
  @JoinColumn()
  @AutoMap(() => DeliveryInfoEntity)
  deliveryInfo: DeliveryInfoEntity;

But if i use '[]' in the decorator it works OK
  @OneToOne(() => DriverEntity, (driver) => driver.deliveryInfo, {
    cascade: true,
    eager: false,
  })
  @AutoMap(() => [DriverEntity])
  //@AutoMap()
  driver: DriverEntity;

Is this a normal behavior?
Am i doing something wrong?

grateful for the help you can give me

### Expected behavior

![image](https://user-images.githubusercontent.com/37184148/200838542-d8e242a0-0e45-4bd0-abeb-43ce379c7238.png)

### Screenshots

![image](https://user-images.githubusercontent.com/37184148/200837022-313a3cba-92bc-462a-87a4-f275ac0c866c.png)
![image](https://user-images.githubusercontent.com/37184148/200837174-792cea89-86d4-4596-9c53-916bab3944a5.png)

![image](https://user-images.githubusercontent.com/37184148/200837058-b9ea121c-d95c-4560-b767-3b6731f7358d.png)
![image](https://user-images.githubusercontent.com/37184148/200837097-7eaf3bfd-a0d8-48e0-95f4-744501fda6a7.png)
![image](https://user-images.githubusercontent.com/37184148/200837246-669dc338-15c7-4832-88e3-e7c3d58f8fef.png)

### Package

- [ ] I don't know.
- [ ] <code>@automapper/core</code>
- [ ] <code>@automapper/classes</code>
- [ ] <code>@automapper/nestjs</code>
- [ ] <code>@automapper/pojos</code>
- [ ] <code>@automapper/mikro</code>
- [ ] <code>@automapper/sequelize</code>
- [ ] Other (see below)

### AutoMapper version

8.7.2

**Comment by nartc** [comment]
Sorry for the very late response. This old entity metadata/circular mapping report is not clearly addressed by the current 9.0 migration on branch `chore/9.0-migrate`, so I am closing it as stale/not planned.
