### ISSUE TITLE
getting dependency error while running unit tests in nestjs

### ISSUE THREAD

**Issue by jayanth-caw** [nartc/mapper#522]
Nest can't resolve dependencies of the SkillService (?, Symbol(SkillRepositorySymbol), CalLoggerService). Please make sure that the argument automapper:nestjs:default at index [0] is available in the RootTestModule context. 

    Potential solutions:
    - If automapper:nestjs:default is a provider, is it part of the current 
RootTestModule?
    - If automapper:nestjs:default is exported from a separate @Module, is that module imported within RootTestModule?
      @Module({
        imports: [ /* the Module containing automapper:nestjs:default */ ]  
      })

      at TestingInjector.lookupComponentInParentModules (../node_modules/@nestjs/core/injector/injector.js:241:19)
      at TestingInjector.resolveComponentInstance (../node_modules/@nestjs/core/injector/injector.js:194:33)
      at TestingInjector.resolveComponentInstance (../node_modules/@nestjs/testing/testing-injector.js:16:45)
      at resolveParam (../node_modules/@nestjs/core/injector/injector.js:116:38)
          at async Promise.all (index 0)
      at TestingInjector.resolveConstructorParams (../node_modules/@nestjs/core/injector/injector.js:131:27)
      at TestingInjector.loadInstance (../node_modules/@nestjs/core/injector/injector.js:57:13)
      at TestingInjector.loadProvider (../node_modules/@nestjs/core/injector/injector.js:84:9)
          at async Promise.all (index 3)

**Comment by nartc** [comment]
Sorry for the very late response. This looks like an old NestJS unit-test setup issue rather than something directly changed by `chore/9.0-migrate`; I am closing it as stale/not planned.
