### ISSUE TITLE
NestJS Error Debug Failure. False expression: Too many nodes written to output

### ISSUE THREAD

**Issue by accarvajal** [nartc/mapper#564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

I'm using package in NestJS v10 and I followed the [documentation](https://automapperts.netlify.app/docs/misc/transformer-plugin).

According samples, to avoid decorating classes with @AutoMap(), I can use a transformer plugin that enables automapper to run a before transformer looking for .entity.ts .model.ts, etc. files and add them to a list for mappings. So I configured nest-cli.json as shown below:

```
{
      "$schema": "https://json.schemastore.org/nest-cli",
      "collection": "@nestjs/schematics",
      "sourceRoot": "src",
      "compilerOptions": {
           "plugins": [
                 "@automapper/classes/transformer-plugin"
           ]
       }
}
```
However when I run the app by using nest start, it throws the error:

 `Error  Debug Failure. False expression: Too many nodes written to output.`

In order to get the app working, I have to remove plugins entry leaving compilerOptions empty.

dependencies used:

```
  "dependencies": {
    "@automapper/classes": "^8.7.7",
    "@automapper/core": "^8.7.7",
    "@automapper/nestjs": "^8.7.7",
    "@nestjs/common": "^10.1.2",
    "@nestjs/config": "^3.0.0",
    "@nestjs/core": "^10.1.2",
    "@nestjs/cqrs": "^10.0.1",
    "@nestjs/jwt": "^10.0.3",
    "@nestjs/passport": "^10.0.0",
    "@nestjs/platform-express": "^10.1.2",
    "@nestjs/swagger": "^7.1.4",
    "@nestjs/throttler": "^4.0.0",
    "@nestjs/typeorm": "^10.0.0",
    "bcrypt": "^5.1.0",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.0",
    "passport": "^0.6.0",
    "passport-jwt": "^4.0.1",
    "passport-local": "^1.0.0",
    "pg": "^8.11.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.2.0",
    "typeorm": "^0.3.16"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.1.10",
    "@nestjs/schematics": "^10.0.1",
    "@nestjs/testing": "^10.1.2",
    "@types/bcrypt": "^5.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "29.5.3",
    "@types/node": "20.4.5",
    "@types/passport-jwt": "^3.0.8",
    "@types/passport-local": "^1.0.35",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^6.2.0",
    "@typescript-eslint/parser": "^6.2.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^5.0.0",
    "jest": "29.6.2",
    "prettier": "^3.0.0",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "29.1.1",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.2.0",
    "typescript": "^5.1.6",
    "vite": "^4.4.7"
  },
```

Thanks for any help

### Mapping configuration

In AppModule:

```
AutomapperModule.forRootAsync({
      useClass: AutomapperConfigService,
}),
```

in AutomapperConfigService:

```
import { classes } from '@automapper/classes';
import { CreateMapperOptions } from '@automapper/core';
import { AutomapperOptionsFactory } from '@automapper/nestjs';
import { Injectable } from '@nestjs/common';

@Injectable()
export class AutomapperConfigService implements AutomapperOptionsFactory {
  createAutomapperOptions():
    | CreateMapperOptions
    | Promise<CreateMapperOptions> {
    return {
      strategyInitializer: classes(),
    };
  }
}
```

### Expected behavior

The error should not be thrown, the application should start running and allow me to run mapper without using the decorator @AutoMap().

### Screenshots

![image](https://github.com/nartc/mapper/assets/20478780/581cdb97-893d-4d95-8924-fa05e93270ed)

### Package

- [ ] I don't know.
- [ ] <code>@automapper/core</code>
- [ ] <code>@automapper/classes</code>
- [X] <code>@automapper/nestjs</code>
- [ ] <code>@automapper/pojos</code>
- [ ] <code>@automapper/mikro</code>
- [ ] <code>@automapper/sequelize</code>
- [ ] Other (see below)

### AutoMapper version

8.7.7

### Additional context

Windows 11

**Comment by accarvajal** [comment]
Due to the nest start command when throws the error get stuck, I noticed that after some time it throwed the following log:

![image](https://github.com/nartc/mapper/assets/20478780/d6adf3ab-2483-49a4-9896-304ebccf5294)

**Comment by yuchuanxi** [comment]
I have the same problem with version 8.7.7

**Comment by davissimo** [comment]
Same issue as well rending it unusable. 

I see that the last commit was in March, and the last issue closed in May.

@nartc Is the library still maintained and to be utilized in production?

**Comment by ttshivers** [comment]
I've fixed this in my fork https://github.com/ttshivers/mapper

**Comment by accarvajal** [comment]
@ttshivers I've added packages: `"@ttshivers/automapper-classes": "^8.8.3",   "@ttshivers/automapper-core": "^8.8.3",  "@ttshivers/automapper-nestjs": "^8.8.3"`, and `"compilerOptions": {
    "plugins": ["@ttshivers/automapper-classes/transformer-plugin"]
  }` in nest-cli.json, however I'm facing this error: `
node_modules\@ttshivers\automapper-core\index.cjs:760 function applyMetadata(model, as, root = true, selfReference = false) {
                        ^
RangeError: Maximum call stack size exceeded
    at applyMetadata (D:\Projects\Repos\Aldemar\VitaliX\server\node_modules\@ttshivers\automapper-core\index.cjs:760:25)
    at applyMetadata (D:\Projects\Repos\Aldemar\VitaliX\server\node_modules\@ttshivers\automapper-core\index.cjs:824:61)
    at applyMetadata (D:\Projects\Repos\Aldemar\VitaliX\server\node_modules\@ttshivers\automapper-core\index.cjs:824:61)
index.cjs:824:61)
    at applyMetadata (D:\Projects\Repos\Aldemar\VitaliX\server\node_modules\@ttshivers\automapper-core\index.cjs:824:61)
    at applyMetadata (D:\Projects\Repos\Aldemar\VitaliX\server\node_modules\@ttshivers\automapper-core\index.cjs:824:61)
    at applyMetadata (D:\Projects\Repos\Aldemar\VitaliX\server\node_modules\@ttshivers\automapper-core\index.cjs:824:61)
`

**Comment by accarvajal** [comment]
@ttshivers, thanks, is working now, I not need to mark properties with @AutoMap, however I'm noticing that I have to mark dates properties with @AutoMap(), both in Dtos and Entities, otherwise it will not map those properties by default, but it's supposed that this type is not required to be marked in the property since is handled by default by the library as it does with primitives.

**Comment by nartc** [comment]
Thanks for reporting this, and sorry for the very late response. The transformer plugin has been updated on branch `chore/9.0-migrate` for newer TypeScript/NestJS compatibility: it now uses public `typescript` imports, has TS 5/6 compatibility updates, and keeps legacy decorator coverage. Closing as addressed by `chore/9.0-migrate`; these changes are not on `main` yet.
